### ISSUE TITLE
Loop playlist 

### ISSUE THREAD

**Issue by Heinrich-XIAO** [gokadzev/Musify#471] opened 2024-12-23 02:59 UTC
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

You can't repeat all even through it looks like that was in the code, as you can't select repeat all. 

### Expected Behavior

Go through all three options when selecting repeat mode. 

### Musify Version

Latest

### Device And Operating System

Huawei

### Android Version You Use

Android 15

**Comment by gokadzev** [comment] 2024-12-23 16:48
Duplicate of #455

**Closed by gokadzev** 2024-12-23 16:48 UTC
Labels: type: bug
