### ISSUE TITLE
[Feature] iOS Build

### ISSUE THREAD

**Issue by SoCuul** [gokadzev/Musify#248] opened 2023-06-09 21:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Logical Improvements

### Credits

SoCuul

### Pain

There is currently no iOS Build of the Musify app, which is a shame for apple users.

### Suggested Solution

It would be great if you could provide an `.ipa` file along with the `.apk` file, so iOS users can sideload the app on their devices.

### Useful resources/references

If you need help testing/configuring the app to work on apple devices, I can totally help you out!

**Comment by DarkCrypt** [comment] 2023-06-11 18:39
Duplicate of #85.

**Comment by gokadzev** [comment] 2023-06-12 21:30
@SoCuul Hello, these several weeks are so busy for me, After these weeks i will see what I can. In general I'm not against releasing Musify for IOS, just before everything, we need Workflow for IOS which will build and upload artifacts (Because it needs MacOS and I don't have it, I guess we need to config signature thing too). After we will manage it, I can make changes in code and wait for your feedback. 

In case of seeing any flutter workflow which builds for IOS or you know how to do it, feel free to open PR or just give me a link and then I will do everything else.

**Comment by gokadzev** [comment] 2023-06-20 04:18
Update: I made little bit research and if I'm not mistaken it's impossible to generate IOS ipa without keys and certificates which cost 99$ (developer account) per year. I'm not expert in IOS things and please correct me if it's wrong

**Comment by SoCuul** [comment] 2023-06-20 06:50
That is completely correct. You must be an apple developer to create a signed application bundle (such as an ipa)

**Comment by gokadzev** [comment] 2023-06-22 17:53
> That is completely correct. You must be an apple developer to create a signed application bundle (such as an ipa)

Then, unfortunately, I can't do it. There is no way I can afford it, and even if I could, I do not receive any financial benefits from this app, so it isn't worth it. I only receive donations, and the number of donations is currently only three, with two of them being made recently.

**Closed** 2023-06-23 19:04 UTC
Labels: enhancement

**Comment by michelmelo** [comment] 2023-10-27 13:06
Hello, I can put it in my account, no problem.

**Comment by michelmelo** [comment] 2023-10-27 13:08
@gokadzev

**Comment by SoCuul** [comment] 2023-10-27 21:03
> > That is completely correct. You must be an apple developer to create a signed application bundle (such as an ipa)
> 
> Then, unfortunately, I can't do it. There is no way I can afford it, and even if I could, I do not receive any financial benefits from this app, so it isn't worth it. I only receive donations, and the number of donations is currently only three, with two of them being made recently.

Now that I think about it, you should be able to create an unsigned ipa, that users themselves sign. Then it would work perfectly!

**Comment by gokadzev** [comment] 2023-10-28 13:45
> > > That is completely correct. You must be an apple developer to create a signed application bundle (such as an ipa)
> > 
> > 
> > Then, unfortunately, I can't do it. There is no way I can afford it, and even if I could, I do not receive any financial benefits from this app, so it isn't worth it. I only receive donations, and the number of donations is currently only three, with two of them being made recently.
> 
> Now that I think about it, you should be able to create an unsigned ipa, that users themselves sign. Then it would work perfectly!

Without a Mac? The comment author above suggested using their account. If they want to take it and build a tested version, they will open a PR with changes and release a build. Otherwise, I can do nothing about it, as releasing an untested app is another thing that I want to avoid.

**Comment by michelmelo** [comment] 2023-10-29 12:20
ok, I'm already working on an iOS version. When I have one created I can make a version available.

**Comment by SoCuul** [comment] 2023-10-30 02:53
> ok, I'm already working on an iOS version. When I have one created I can make a version available.

Oh cool, thanks!

**Comment by narakai** [comment] 2024-02-01 03:19
I have successfully build iOS, just run: flutter create ios and then run: cd ios, pod install, you should able to install ios version. But I stuck with  a problem that just_audio won't play the audio url.

**Comment by gokadzev** [comment] 2024-02-01 07:53
> I have successfully build iOS, just run: flutter create ios and then run: cd ios, pod install, you should able to install ios version. But I stuck with a problem that just_audio won't play the audio url.
> 
> Log is:
> 
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null) flutter: [2024-02-01 11:33:22.188169] Error playing song:(-11828) Cannot Open flutter: #0 AudioPlayer._load (package:just_audio/just_audio.dart:869) flutter: flutter: #1 AudioPlayer.load (package:just_audio/just_audio.dart:799) flutter: flutter: #2 AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:774) flutter: flutter: #3 MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:248)

Unfortunately, without seeing and understanding the iOS code changes, I won't be able to determine exactly what the problem is. However, since it works for Android, the issue is likely located either in the iOS code or on the package side.
